export enum LogMessageType {
  RED = 'red',
  BLUE = 'blue',
  SYSTEM = 'system',
}

export const LogMessageKeys = {
  LOG_START_GAME: 'LOG_START_GAME',

  LOG_HINT_RED: 'LOG_HINT_RED',
  LOG_HINT_BLUE: 'LOG_HINT_BLUE',
  LOG_HINT_TIMEOUT: 'LOG_HINT_TIMEOUT',
  LOG_HINT_PHASE_STARTED: 'LOG_HINT_PHASE_STARTED',
  LOG_HINT_PHASE_ENDED: 'LOG_HINT_PHASE_ENDED',
  LOG_HINT_REQUEST: 'LOG_HINT_REQUEST',
  LOG_HINT_GIVEN: 'LOG_HINT_GIVEN',

  LOG_VOTE_STARTED: 'LOG_VOTE_STARTED',
  LOG_VOTE_ENDED: 'LOG_VOTE_ENDED',
  LOG_VOTE_CHANGED: 'LOG_VOTE_CHANGED',

  LOG_OWN_CARD_CHOSEN_RED: 'LOG_OWN_CARD_CHOSEN_RED',
  LOG_OWN_CARD_CHOSEN_BLUE: 'LOG_OWN_CARD_CHOSEN_BLUE',
  LOG_OTHER_CARD_CHOSEN_RED: 'LOG_OTHER_CARD_CHOSEN_RED',
  LOG_OTHER_CARD_CHOSEN_BLUE: 'LOG_OTHER_CARD_CHOSEN_BLUE',
  LOG_OWN_CARD_CHOSEN_RED_NEITRAL: 'LOG_OWN_CARD_CHOSEN_RED_NEITRAL',
  LOG_OWN_CARD_CHOSEN_BLUE_NEITRAL: 'LOG_OWN_CARD_CHOSEN_BLUE_NEITRAL',

  LOG_CARD_REVEALED_RED: 'LOG_CARD_REVEALED_RED',
  LOG_CARD_REVEALED_BLUE: 'LOG_CARD_REVEALED_BLUE',
  LOG_CARD_REVEALED_NEUTRAL: 'LOG_CARD_REVEALED_NEUTRAL',
  LOG_CARD_REVEALED_BOMB: 'LOG_CARD_REVEALED_BOMB',

  LOG_CHECKING_ANSWER_RED: 'LOG_CHECKING_ANSWER_RED',
  LOG_CHECKING_ANSWER_BLUE: 'LOG_CHECKING_ANSWER_BLUE',
  LOG_ANSWER_COUNTED_RED: 'LOG_ANSWER_COUNTED_RED',
  LOG_ANSWER_COUNTED_BLUE: 'LOG_ANSWER_COUNTED_BLUE',
  LOG_SCORE_POINT: 'LOG_SCORE_POINT',

  LOG_ANSWER_TIMEOUT: 'LOG_ANSWER_TIMEOUT',
  LOG_CHECK_TIMEOUT: 'LOG_CHECK_TIMEOUT',

  LOG_TURN_CHANGED_RED: 'LOG_TURN_CHANGED_RED',
  LOG_TURN_CHANGED_BLUE: 'LOG_TURN_CHANGED_BLUE',

  LOG_GAME_END_RED_WIN: 'LOG_GAME_END_RED_WIN',
  LOG_GAME_END_BLUE_WIN: 'LOG_GAME_END_BLUE_WIN',
} as const;

export type LogMessageKey = (typeof LogMessageKeys)[keyof typeof LogMessageKeys];

export type LogMessage = {
  type: LogMessageType;
  key: LogMessageKey;
  info: string | null;
};
